/// <reference types="react" />
import { SliderProps, InputNumberProps, SwitchProps, TextAreaProps, CheckboxGroupProps, TreeSelectProps } from '@arco-design/web-react';
import { ImageUploaderProps } from './ImageUploader';
import { UploadFieldProps } from './UploadField';
import { SelectProps } from './Select';
import { RadioGroupProps } from './RadioGroup';
import enhancer from './enhancer';
import { InputProps } from './Input';
import { InputWithUnitProps } from './InputWithUnit';
import { EditTabProps } from './EditTab';
import { EditGridTabProps } from './EditGridTab';
import { InlineTextProps } from './InlineTextField';
import { AutoCompleteProps } from './AutoComplete';
import { InputSearchProps } from '@arco-design/web-react/es/Input';
import { ColorPickerField } from './ColorPickerField';
export { RichTextField } from './RichTextField';
export declare const TextField: (props: import("./enhancer").EnhancerProps & Omit<InputProps, "onChange" | "value" | "mutators">) => import("react").JSX.Element;
export declare const InputWithUnitField: (props: import("./enhancer").EnhancerProps & Omit<InputWithUnitProps, "onChange" | "value" | "mutators">) => import("react").JSX.Element;
export declare const SearchField: (props: import("./enhancer").EnhancerProps & Omit<InputSearchProps, "onChange" | "value" | "mutators">) => import("react").JSX.Element;
export declare const TextAreaField: (props: import("./enhancer").EnhancerProps & Omit<TextAreaProps, "onChange" | "value" | "mutators">) => import("react").JSX.Element;
export declare const NumberField: (props: import("./enhancer").EnhancerProps & Omit<InputNumberProps, "onChange" | "value" | "mutators">) => import("react").JSX.Element;
export declare const SliderField: (props: import("./enhancer").EnhancerProps & Omit<SliderProps, "onChange" | "value" | "mutators">) => import("react").JSX.Element;
export declare const UploadField: (props: import("./enhancer").EnhancerProps & Omit<UploadFieldProps, "onChange" | "value" | "mutators">) => import("react").JSX.Element;
export declare const ImageUploaderField: (props: import("./enhancer").EnhancerProps & Omit<ImageUploaderProps, "onChange" | "value" | "mutators">) => import("react").JSX.Element;
export declare const SelectField: (props: import("./enhancer").EnhancerProps & Omit<SelectProps, "onChange" | "value" | "mutators">) => import("react").JSX.Element;
export declare const TreeSelectField: (props: import("./enhancer").EnhancerProps & Omit<TreeSelectProps, "onChange" | "value" | "mutators">) => import("react").JSX.Element;
export declare const AutoCompleteField: (props: import("./enhancer").EnhancerProps & Omit<AutoCompleteProps, "onChange" | "value" | "mutators">) => import("react").JSX.Element;
export declare const RadioGroupField: (props: import("./enhancer").EnhancerProps & Omit<RadioGroupProps, "onChange" | "value" | "mutators">) => import("react").JSX.Element;
export declare const SwitchField: (props: import("./enhancer").EnhancerProps & Omit<SwitchProps, "onChange" | "value" | "mutators">) => import("react").JSX.Element;
export declare const CheckboxField: (props: import("./enhancer").EnhancerProps & Omit<CheckboxGroupProps<any>, "onChange" | "value" | "mutators">) => import("react").JSX.Element;
export declare const EditTabField: (props: import("./enhancer").EnhancerProps & Omit<EditTabProps<any>, "onChange" | "value" | "mutators">) => import("react").JSX.Element;
export declare const EditGridTabField: (props: import("./enhancer").EnhancerProps & Omit<EditGridTabProps<any>, "onChange" | "value" | "mutators">) => import("react").JSX.Element;
export declare const InlineTextField: (props: import("./enhancer").EnhancerProps & Omit<InlineTextProps, "onChange" | "value" | "mutators">) => import("react").JSX.Element;
export { ColorPickerField };
export { enhancer };
